// admin/js/delivery.mjs
import { watchOrders } from '../../js/store.mjs';
import { watchDeliveryPersonnel, addDeliveryPersonnel, updateDeliveryPersonnel, deleteDeliveryPersonnel, watchDeliveryTypes, addDeliveryType, updateDeliveryType, deleteDeliveryType, watchDeliveryCheckpoints, addDeliveryCheckpoint, updateDeliveryCheckpoint, deleteDeliveryCheckpoint, createDelivery, watchDeliveries, updateDelivery } from './delivery-store.mjs';
import { DELIVERY_STATES, DELIVERY_STATE_LABELS, isOrderEligibleForDelivery, canTransitionDelivery, buildDeliveryFromOrder } from './delivery-lifecycle.mjs';

const root=document.getElementById('deliveryContent');
if(!root) throw new Error('Delivery panel is missing from admin/delivery.html');
let personnel=[],types=[],checkpoints=[],orders=[],deliveries=[];let unsubs=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`₦${Number(v||0).toLocaleString()}`;
const stateLabel=s=>DELIVERY_STATE_LABELS[s]||s||'Unknown';
function eligible(){return orders.filter(isOrderEligibleForDelivery)}
function render(){root.innerHTML=`<div class="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5"><div class="bg-white rounded-2xl p-4 shadow-sm"><small>Eligible orders</small><b>${eligible().length}</b></div><div class="bg-white rounded-2xl p-4 shadow-sm"><small>Active deliveries</small><b>${deliveries.filter(d=>!['delivered','cancelled','returned'].includes(d.status)).length}</b></div><div class="bg-white rounded-2xl p-4 shadow-sm"><small>Personnel</small><b>${personnel.filter(p=>p.active!==false).length}</b></div><div class="bg-white rounded-2xl p-4 shadow-sm"><small>Checkpoints</small><b>${checkpoints.length}</b></div></div><div class="flex gap-2 overflow-x-auto mb-4"><button class="sub active" data-section="queue">Delivery Queue</button><button class="sub" data-section="people">Personnel</button><button class="sub" data-section="types">Types</button><button class="sub" data-section="checkpoints">Checkpoints</button></div><div id="deliverySubpanel"></div>`;document.querySelectorAll('.sub').forEach(b=>{b.className='sub px-4 py-2 rounded-full bg-gray-100 text-xs font-bold whitespace-nowrap';if(b.dataset.section==='queue')b.classList.add('bg-gray-900','text-white');b.onclick=()=>{document.querySelectorAll('.sub').forEach(x=>{x.className='sub px-4 py-2 rounded-full bg-gray-100 text-xs font-bold whitespace-nowrap'});b.classList.add('bg-gray-900','text-white');section(b.dataset.section)}});section('queue')}
function section(s){const e=document.getElementById('deliverySubpanel');if(s==='queue')queue(e);if(s==='people')people(e);if(s==='types')typesUI(e);if(s==='checkpoints')checkpointsUI(e)}
function queue(el){const list=eligible();el.innerHTML=`<div class="bg-white rounded-2xl p-5 shadow-sm mb-4"><h2 class="font-black text-lg">Delivery Queue</h2><p class="text-xs text-gray-400">Only confirmed/shipped orders can enter delivery.</p></div><div class="grid gap-3">${list.length?list.map(card).join(''):'<div class="bg-white rounded-2xl p-8 text-center text-sm text-gray-400">No eligible orders.</div>'}</div>`;el.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>assign(b.dataset.create));el.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>advance(b.dataset.id,b.dataset.next));el.querySelectorAll('[data-checkpoint]').forEach(b=>b.onclick=()=>checkpoint(b.dataset.id));}
function card(o){let d=deliveries.find(x=>x.orderId===o.id&&!['cancelled','returned'].includes(x.status));if(!d)return `<article class="bg-white rounded-2xl p-4 shadow-sm"><div class="flex justify-between"><div><b>${esc(o.trackingCode||o.id)}</b><p class="text-sm">${esc(o.customerName||o.customer?.name||'Customer')}</p><p class="text-xs text-gray-400">${esc(o.address||o.customer?.address||'No address')}</p></div><b>${money(o.total||o.amount)}</b></div><div class="grid md:grid-cols-3 gap-2 mt-4"><select id="p-${o.id}" class="border rounded-xl p-2 text-xs"><option value="">Assign personnel</option>${personnel.filter(p=>p.active!==false).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select><select id="t-${o.id}" class="border rounded-xl p-2 text-xs"><option value="">Delivery type</option>${types.filter(t=>t.active!==false).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select><button data-create="${esc(o.id)}" class="bg-gray-900 text-white rounded-xl text-xs font-bold">Create Delivery</button></div></article>`;return deliveryCard(d,o)}
function deliveryCard(d,o){const next={ready:'assigned',assigned:'picked_up',picked_up:'in_transit',in_transit:'checkpoint',checkpoint:'delivered',failed:'assigned',returned:'assigned'}[d.status];const p=personnel.find(x=>x.id===d.assignedTo);const t=types.find(x=>x.id===d.deliveryTypeId||x.id===d.deliveryType);return `<article class="bg-white rounded-2xl p-4 shadow-sm"><div class="flex justify-between gap-3"><div><b>${esc(o.trackingCode||d.orderId)}</b><p class="text-sm">${esc(d.customerName||o.customerName||'Customer')}</p><p class="text-xs text-gray-400">${esc(d.address||o.address||'No address')}</p></div><span class="px-2 py-1 rounded-full bg-teal-50 text-teal-700 text-[10px] font-black">${esc(stateLabel(d.status))}</span></div><div class="grid md:grid-cols-3 gap-2 mt-4 text-xs"><div class="bg-gray-50 rounded-xl p-3"><b>Personnel</b><br>${esc(p?.name||d.assignedToName||'Unassigned')}</div><div class="bg-gray-50 rounded-xl p-3"><b>Type</b><br>${esc(t?.name||d.deliveryType||'Not selected')}</div><div class="bg-gray-50 rounded-xl p-3"><b>Checkpoint</b><br>${esc(checkpoints.find(c=>c.id===d.lastCheckpointId)?.name||'None')}</div></div><div class="flex flex-wrap gap-2 mt-3">${next?`<button data-id="${d.id}" data-next="${next}" class="bg-gray-900 text-white rounded-xl px-3 py-2 text-xs font-bold">${esc(stateLabel(next))}</button>`:''}${['in_transit','checkpoint'].includes(d.status)?`<button data-id="${d.id}" data-checkpoint="1" class="border rounded-xl px-3 py-2 text-xs font-bold">Record Checkpoint</button>`:''}${['picked_up','in_transit','checkpoint'].includes(d.status)?`<button data-id="${d.id}" data-next="failed" class="border border-red-200 text-red-600 rounded-xl px-3 py-2 text-xs font-bold">Failed</button>`:''}${['picked_up','in_transit','checkpoint'].includes(d.status)?`<button data-id="${d.id}" data-next="returned" class="border border-amber-200 text-amber-700 rounded-xl px-3 py-2 text-xs font-bold">Returned</button>`:''}</div></article>`}
async function assign(orderId){const o=orders.find(x=>x.id===orderId);const pid=document.getElementById(`p-${orderId}`).value;const tid=document.getElementById(`t-${orderId}`).value;if(!pid||!tid)return alert('Select personnel and delivery type.');const p=personnel.find(x=>x.id===pid),t=types.find(x=>x.id===tid);try{await createDelivery(buildDeliveryFromOrder(o,{deliveryTypeId:tid,deliveryType:t?.name||'',personnelId:pid,personnelName:p?.name||''}));}catch(e){alert(e.message)}}
async function advance(id,next){const d=deliveries.find(x=>x.id===id);if(!d||!canTransitionDelivery(d.status,next))return alert(`Cannot move from ${stateLabel(d?.status)} to ${stateLabel(next)}.`);const now=Date.now(),patch={status:next,updatedAt:now};if(next==='assigned')patch.assignedAt=d.assignedAt||now;if(next==='picked_up')patch.pickedUpAt=now;if(next==='in_transit')patch.outForDeliveryAt=now;if(next==='delivered')patch.deliveredAt=now;if(next==='failed')patch.failedAt=now;if(next==='returned')patch.returnedAt=now;await updateDelivery(id,patch)}
async function checkpoint(id){const d=deliveries.find(x=>x.id===id);if(!d)return;const options=checkpoints.map(c=>`${c.id}: ${c.name}`).join('\n');const selected=prompt(`Checkpoint ID:\n${options}`);if(!selected)return;const cid=selected.split(':')[0].trim();if(!checkpoints.some(c=>c.id===cid))return alert('Invalid checkpoint.');await updateDelivery(id,{status:d.status==='in_transit'?'checkpoint':d.status,lastCheckpointId:cid,lastCheckpointAt:Date.now(),updatedAt:Date.now(),checkpoints:[...(d.checkpoints||[]),{checkpointId:cid,at:Date.now()}]})}
async function personPrompt(p){const n=prompt('Name',p?.name||'');if(!n)return;const ph=prompt('Phone',p?.phone||'')||'',em=prompt('Email',p?.email||'')||'',a=confirm('Active?');if(p)await updateDeliveryPersonnel(p.id,{name:n,phone:ph,email:em,active:a,updatedAt:Date.now()});else await addDeliveryPersonnel({name:n,phone:ph,email:em,active:a,createdAt:Date.now()})}
function people(el){el.innerHTML=`<div class="bg-white rounded-2xl p-5 shadow-sm mb-4 flex justify-between"><div><b>Delivery Personnel</b><p class="text-xs text-gray-400">Manage your team.</p></div><button id="addP" class="bg-gray-900 text-white rounded-xl px-4 py-2 text-xs font-bold">+ Add</button></div>${personnel.map(p=>`<div class="bg-white rounded-2xl p-4 mb-2 flex justify-between"><div><b>${esc(p.name)}</b><p class="text-xs text-gray-400">${esc(p.phone||'No phone')} · ${esc(p.email||'No email')}</p></div><button data-edit="${p.id}" class="text-xs font-bold text-teal-600">Edit</button></div>`).join('')}`;el.querySelector('#addP').onclick=()=>personPrompt();el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>personPrompt(personnel.find(p=>p.id===b.dataset.edit)))}
function typesUI(el){el.innerHTML=`<div class="bg-white rounded-2xl p-5 shadow-sm mb-4 flex justify-between"><b>Delivery Types</b><button id="addT" class="bg-gray-900 text-white rounded-xl px-4 py-2 text-xs font-bold">+ Add</button></div>${types.map(t=>`<div class="bg-white rounded-2xl p-4 mb-2"><b>${esc(t.name)}</b><p class="text-xs text-gray-400">${esc(t.description||'')}</p></div>`).join('')}`;el.querySelector('#addT').onclick=async()=>{const n=prompt('Type name');if(n)await addDeliveryType({name:n,description:prompt('Description')||'',active:true,createdAt:Date.now()})}}
function checkpointsUI(el){el.innerHTML=`<div class="bg-white rounded-2xl p-5 shadow-sm mb-4 flex justify-between"><b>Delivery Checkpoints</b><button id="addC" class="bg-gray-900 text-white rounded-xl px-4 py-2 text-xs font-bold">+ Add</button></div>${checkpoints.map(c=>`<div class="bg-white rounded-2xl p-4 mb-2"><b>${esc(c.name)}</b><p class="text-xs text-gray-400">${esc(c.address||c.description||'')}</p></div>`).join('')}`;el.querySelector('#addC').onclick=async()=>{const n=prompt('Checkpoint name');if(n)await addDeliveryCheckpoint({name:n,address:prompt('Address / description')||'',active:true,createdAt:Date.now()})}}
unsubs=[watchDeliveryPersonnel(v=>{personnel=v;render()}),watchDeliveryTypes(v=>{types=v;render()}),watchDeliveryCheckpoints(v=>{checkpoints=v;render()}),watchOrders(v=>{orders=v;render()}),watchDeliveries(v=>{deliveries=v;render()})];window.addEventListener('beforeunload',()=>unsubs.forEach(fn=>fn&&fn()));render();
